using Zenject;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.InstallerGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Entitas.Generated.Installer {
	public static class EcsGameSystems {
		public static void Install(DiContainer container, bool isDebug = true){
		}

	}
}