using Ecs.Item.Systems;
using Zenject;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.InstallerGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Entitas.Generated.Installer {
	public static class EcsGameSystems {
		public static void Install(DiContainer container, bool isDebug = true){
			Normal(container, isDebug);
		}

		private static void Normal(DiContainer container, bool isDebug) {
 
			//  1000
			container.BindInterfacesAndSelfTo<RemoveItemSystem>().AsSingle();	// 1000 
		 }

	}
}