using Ecs.Item.Systems;
using Ecs.Game.System;
using Zenject;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.InstallerGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Entitas.Generated.Installer {
	public static class EcsGameSystems {
		public static void Install(DiContainer container, bool isDebug = true){
			Normal(container, isDebug);
		}

		private static void Normal(DiContainer container, bool isDebug) {
 
			//  0100
			container.BindInterfacesAndSelfTo<InstantiateSystem>().AsSingle();	// 0100 

			//  0300
			container.BindInterfacesAndSelfTo<ApplyVelocityUnitSystem>().AsSingle();	// 0300 

			//  0500
			container.BindInterfacesAndSelfTo<LowHealthSystem>().AsSingle();	// 0500 

			//  0700
			container.BindInterfacesAndSelfTo<MoveUnitSystem>().AsSingle();	// 0700 

			//  0780
			container.BindInterfacesAndSelfTo<CameraMoveSystem>().AsSingle();	// 0780 

			//  1000
			container.BindInterfacesAndSelfTo<RemoveItemSystem>().AsSingle();	// 1000 
		 }

	}
}